spring.application.name=CIA
spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_PASSWORD}
spring.data.neo4j.database=${SPRING_NEO4J_DATABASE}
app.basepath=/tmp/cia